### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by goodtogood** [anydream/il2cpp#2]
如题，谢谢

**Comment by anydream** [comment]
设置 'test' 为启动项目直接 Ctrl+F5 就行啦~
没有 clang 的话先去装一个, C++ 编译器目前钦定了 clang. (也可以自己编译一份 llvm/clang)

**Comment by anydream** [comment]
暂时没有做独立的代码生成工具, 所以目前只能在 test 里进行测试.
测试案例代码在 testcase 工程内, 标注了 [CodeGen] 的类便是.
