### ISSUE TITLE
能支持ios和android 么？

### ISSUE THREAD

**Issue by srxqds** [anydream/il2cpp#3]
微软的coreclr和corrt都不支持ios，好像也没有想法支持，估计都打算交给mono了
你这个能支持ios和android 导出么 如果可以，想在游戏引擎层支持这个？

**Comment by anydream** [comment]
@srxqds 支持的, 但是需要你针对平台写不同的启动壳子, 即Activity

**Comment by srxqds** [comment]
嗯，看到你这个实现很震惊，太牛了，想问下这个支持.net core的runtime和library 么？
我看微软貌似不打算搞这个corert也没有计划支持全平台，又不想去用mono

**Comment by srxqds** [comment]
能简单介绍下il2cpp的原理么？

**Comment by anydream** [comment]
@srxqds 程序员不喜欢写文档, 你懂的 :smile:, 有时间的话我会大概写一下流程...

**Comment by anydream** [comment]
@srxqds 已经把clang工具链添加到工程了, 现在无需另外安装clang环境.
大致的运行测试流程已经更新在 ``README.md`` 里, 如果有什么疑问可以问我.
